import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,Map,CalendarCheck,BriefcaseBusiness,TrainFront,Car,Plane,House,Soup,Star,Camera,Check,ChevronRight,Printer,Compass} from 'lucide-react';
import {days,trip,bookings,packing,transportRows,statusLabels,type BookingStatus,type BookingItem,type Info,type ItineraryDay} from './data/itinerary';
import TerrainMap from './components/TerrainMap';
const routeIds=['overview',...days.map(d=>d.id),'bookings','checklist','transport'];
const readRoute=()=>location.hash.replace(/^#\//,'')||'overview';
function readStored<T>(key:string,fallback:T,validate:(x:unknown)=>boolean):T{try{const raw=JSON.parse(localStorage.getItem(key)||'null');return validate(raw)?raw:fallback;}catch{return fallback;}}
const isRecord=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const validStatuses=(x:unknown)=>isRecord(x)&&Object.entries(x).every(([k,v])=>bookings.some(b=>b.id===k)&&typeof v==='string'&&Object.hasOwn(statusLabels,v));
const packingItems=packing.flatMap(g=>g.items);
const validChecks=(x:unknown)=>isRecord(x)&&Object.entries(x).every(([k,v])=>packingItems.includes(k)&&typeof v==='boolean');
function Card({info}:{info:Info}){const Icon={activity:Camera,hotel:House,food:Soup,transport:Car,tip:Star}[info.kind||'activity'];return <section className={'info-card '+(info.kind||'activity')}><div className="card-heading"><span className="round-icon"><Icon size={21} aria-hidden="true"/></span><h3>{info.title}</h3></div><div className="card-body">{info.tag&&<span className="tag">{info.tag}</span>}{info.lines.map((line,i)=><p key={i}>{line}</p>)}{info.action&&(info.url?<a className="pill" href={info.url} target="_blank" rel="noreferrer">{info.action}<ArrowRight size={15}/></a>:<button className="pill unavailable" disabled>{info.action} · 待开放</button>)}</div></section>}
function SmallMap({day}:{day:ItineraryDay}){return <figure className="small-map"><p className="eyebrow">TODAY’S ROUTE</p><svg viewBox={`0 0 340 ${day.route.length*56+4}`} role="img" aria-label={day.route.map(s=>s.name).join('到')}>{day.route.map((s,i)=>{const y=26+i*56;return <g key={s.name}>{i>0&&<><path d={`M25 ${y-50}V${y-7}`} stroke={s.mode==='drive'?'#12365e':s.mode==='train'||s.mode==='flight'?'#b62d25':'#7f796d'} strokeWidth="2" strokeDasharray={s.mode==='drive'?undefined:s.mode==='taxi'?'3 3':'7 4'}/><text x="230" y={y-23} className="map-note">{{drive:'自驾',flight:'飞机',train:'动车 / 高铁',taxi:'接送 / 市内交通'}[s.mode||'taxi']}</text></>}<circle cx="25" cy={y} r="5" fill={i===0?'#b62d25':'#12365e'}/><text x="45" y={y+5} className="day-map-label">{s.name}</text></g>})}</svg><figcaption>顺序示意 · 实际位置及车程待确认</figcaption></figure>}
function BookingRow({item,status,onChange}:{item:BookingItem;status:BookingStatus;onChange:(id:string,value:BookingStatus)=>void}){return <article className="booking-row"><div className="booking-meta"><span>{item.date} · {item.category}</span>{item.priority==='high'&&<span className="priority">优先订</span>}</div><h3>{item.title}</h3><p>{item.note}</p><div className="booking-actions"><label className="sr-only" htmlFor={'booking-'+item.id}>预订状态：{item.title}</label><select id={'booking-'+item.id} value={status} onChange={e=>onChange(item.id,e.target.value as BookingStatus)}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{item.url?<a href={item.url} className="text-link" target="_blank" rel="noreferrer">查看预订<ArrowRight size={15}/></a>:<span className="muted">商家链接待确认</span>}</div></article>}
function DayPage({day,statuses,onStatus}:{day:ItineraryDay;statuses:Record<string,BookingStatus>;onStatus:(id:string,s:BookingStatus)=>void}){const index=days.findIndex(x=>x.id===day.id);return <><div className="day-title"><p className="eyebrow red">{day.label} · {day.date} · {day.weekday}</p><h2>{day.title}</h2><p className="subtitle">{day.subtitle}</p></div><SmallMap day={day}/><section className="daily-plan"><p className="eyebrow red">DAILY PLAN</p><h3>当天这样走</h3><p>{day.intro}</p></section><section className="timeline" aria-label="当天时间轴">{day.timeline.map((t,i)=><div className="timeline-item" key={i}><span className="timeline-dot"/><p className="time">{t.time}</p><h3>{t.title}</h3>{t.note&&<p className="muted">{t.note}</p>}</div>)}</section>{day.cards.map((c,i)=><Card info={c} key={i}/>)}<section className="day-booking"><div className="section-heading"><CalendarCheck size={21}/><h3>这一天，提前订</h3></div>{day.bookingIds.map(id=>{const b=bookings.find(x=>x.id===id)!;return <BookingRow key={id} item={b} status={statuses[id]||b.status} onChange={onStatus}/>})}</section><Card info={{kind:'tip',title:'同行小提示',lines:day.tips}}/><div className="bottom-nav"><a href={'#/'+(index===0?'overview':days[index-1].id)}><ArrowLeft size={18}/>{index===0?'返回总览':'前一天'}</a><a href={'#/'+(index===days.length-1?'overview':days[index+1].id)}>{index===days.length-1?'返回首页':'后一天'}<ArrowRight size={18}/></a></div></>}
export default function App(){const [route,setRoute]=useState(readRoute);const [statuses,setStatuses]=useState<Record<string,BookingStatus>>(()=>readStored('mongolia:bookings:v1',{},validStatuses));const [checked,setChecked]=useState<Record<string,boolean>>(()=>readStored('mongolia:packing:v1',{},validChecks));const [storageWarning,setStorageWarning]=useState(false);const [printing,setPrinting]=useState(false);const nav=useRef<HTMLElement>(null);const touch=useRef<{x:number;y:number}|null>(null);
useEffect(()=>{const change=()=>{setRoute(readRoute());window.scrollTo({top:0,behavior:'instant'});};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
useEffect(()=>{const item=nav.current?.querySelector<HTMLElement>('[aria-current="page"]');if(item&&nav.current)nav.current.scrollTo({left:item.offsetLeft-nav.current.clientWidth/2+item.clientWidth/2,behavior:'smooth'});},[route]);
useEffect(()=>{try{localStorage.setItem('mongolia:bookings:v1',JSON.stringify(statuses));localStorage.setItem('mongolia:packing:v1',JSON.stringify(checked));setStorageWarning(false);}catch{setStorageWarning(true);}},[statuses,checked]);
useEffect(()=>{if(printing){const timer=setTimeout(()=>window.print(),150);const end=()=>setPrinting(false);window.addEventListener('afterprint',end);return()=>{clearTimeout(timer);window.removeEventListener('afterprint',end);};}},[printing]);
const onStatus=(id:string,value:BookingStatus)=>{if(!bookings.some(b=>b.id===id)||!Object.hasOwn(statusLabels,value))throw new Error('无效的预订项或状态');setStatuses(s=>({...s,[id]:value}));};
useEffect(()=>{type MC={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:MC}).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();const tools=[{name:'read_trip_plan',description:'读取旅行日期、每日行程和本设备的预订记录。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({days,bookings:bookings.map(b=>({...b,status:statuses[b.id]||b.status}))})},{name:'update_local_booking_status',description:'仅更新本设备的预订记录，不向商家下单，不付款，不同步同行者。',inputSchema:{type:'object',properties:{id:{type:'string',enum:bookings.map(b=>b.id)},status:{type:'string',enum:Object.keys(statusLabels)}},required:['id','status'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!isRecord(input)||typeof input.id!=='string'||typeof input.status!=='string'||!bookings.some(b=>b.id===input.id)||!Object.hasOwn(statusLabels,input.status))throw new Error('无效预订项或状态');onStatus(input.id,input.status as BookingStatus);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {id:input.id,status:input.status,scope:'local-device'};}}];for(const tool of tools)try{void Promise.resolve(ctx.registerTool(tool,{signal:ac.signal})).catch(()=>{});}catch{/* Optional browser API. */}return()=>ac.abort();},[statuses]);
const currentDay=days.find(d=>d.id===route);const todo=bookings.filter(b=>(statuses[b.id]||b.status)==='todo').length;const confirmed=bookings.filter(b=>(statuses[b.id]||b.status)==='confirmed').length;const packed=packingItems.filter(x=>checked[x]).length;
const quick:[string,string,ReactNode][]=[['start','完整行程',<Map size={21}/>],['bookings','需要预订',<CalendarCheck size={21}/>],['transport','交通总览',<TrainFront size={21}/>],['checklist','行李清单',<BriefcaseBusiness size={21}/>]];
const swipe=(x:number,y:number)=>{if(!touch.current||!currentDay)return;const dx=x-touch.current.x,dy=y-touch.current.y;touch.current=null;if(Math.abs(dx)<80||Math.abs(dy)>45)return;const i=days.indexOf(currentDay)+(dx<0?1:-1);if(i>=0&&i<days.length)location.hash='/'+days[i].id;};
return <div className="app-shell"><header><div className="header-top"><p className="eyebrow">2026 · INNER MONGOLIA JOURNEY</p><button className="print-button" aria-label="打印全套行程" onClick={()=>setPrinting(true)}><Printer size={17}/></button></div><a href="#/overview" aria-label="旅行总览"><h1>内蒙古<br/><span>7天6晚旅行</span></h1></a><p>{trip.dates} · {trip.party}<br/>长沙往返呼和浩特 · 高铁＋短期租车</p></header><nav className="day-tabs" ref={nav} aria-label="日期导航"><a className={route==='overview'?'active':''} aria-current={route==='overview'?'page':undefined} href="#/overview">总览<small>旅程地图</small></a>{days.map(d=><a className={route===d.id?'active':''} aria-current={route===d.id?'page':undefined} key={d.id} href={'#/'+d.id}>{d.label}<small>{d.date}</small></a>)}</nav><div className="route-strip">{trip.route}</div>{storageWarning&&<div className="storage-warning" role="status">当前浏览器无法保存记录，关闭页面后勾选与状态可能丢失。</div>}<main key={route} onTouchStart={e=>{touch.current=null;if((e.target as HTMLElement).closest('a,button,select,input,nav,svg'))return;touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY};}} onTouchEnd={e=>swipe(e.changedTouches[0].clientX,e.changedTouches[0].clientY)}>
{route==='overview'&&<><p className="eyebrow red">THE JOURNEY</p><h2>草原、火山与沙漠</h2><p className="muted">五天尽兴，两天启程与归来。</p><div className="quick-grid">{quick.map(([id,title,icon])=><a href={'#/'+id} key={id}>{icon}<span>{title}</span><ChevronRight size={14}/></a>)}</div><figure className="hero-art"><img src="./images/autumn.webp" width="1200" height="800" alt="内蒙古秋日旅行意境插画：草原上的马与蒙古包，远处火山和金色沙丘"/><figcaption>秋日草原 · 火山地貌 · 沙漠星空 <span>旅行意境插画</span></figcaption></figure><TerrainMap/><section className="highlights"><p className="eyebrow red">MOMENTS TO REMEMBER</p><h3>这趟旅行，最期待的事</h3><div><span>01</span><p>在草原上，真正骑一次马</p></div><div><span>02</span><p>穿蒙古袍，从旅拍走到篝火旁</p></div><div><span>03</span><p>走过火山，把夜晚留给沙漠</p></div></section><div className="section-heading"><Compass size={20}/><h3>七天这样串起来</h3></div><div className="day-index">{days.map(d=><a href={'#/'+d.id} key={d.id}><span className="day-number">{d.label}<small>{d.date}</small></span><div><strong>{d.title}</strong><p>{d.subtitle}</p></div><ChevronRight size={16}/></a>)}</div><Card info={{kind:'transport',title:'不用全程自驾',lines:['10/3—10/5，租车串起草原与火山。','10/6—10/7，动车 / 高铁＋预约接送往返沙漠。','具体车次、取还车与接送时间待预订。']}}/><a className="booking-summary" href="#/bookings"><div><p className="eyebrow">BEFORE WE GO</p><h3>出发前要订什么？</h3><p>{todo}项待订 · {confirmed}项已确认</p></div><ArrowRight size={24}/></a><p className="muted">当前为讨论方案，行程时刻及运营安排待核实。项目较多，优先保留大家最想玩的。</p></>}
{currentDay&&<DayPage day={currentDay} statuses={statuses} onStatus={onStatus}/>}
{route==='bookings'&&<><p className="eyebrow red">BEFORE WE GO</p><h2>出发前要订什么？</h2><div className="stats"><span><b>{todo}</b> 待预订</span><span><b>{confirmed}</b> 已确认</span></div><p className="muted">状态仅保存在当前设备和浏览器，不会同步给同行朋友。修改状态不会向商家下单。</p>{(['住宿','租车','项目','门票','交通'] as const).map(cat=><section key={cat} className="booking-group"><h3 className="group-title">{cat}<span>{bookings.filter(b=>b.category===cat).length} 项</span></h3>{bookings.filter(b=>b.category===cat).map(b=><BookingRow key={b.id} item={b} status={statuses[b.id]||b.status} onChange={onStatus}/>)}</section>)}</>}
{route==='transport'&&<><p className="eyebrow red">ON THE ROAD</p><h2>交通总览</h2><p className="muted">飞机往返 · 草原段自驾 · 沙漠段高铁＋接送</p><div className="transport-list">{transportRows.map(([date,path,mode,id],i)=><article key={i}><div className="transport-date">{date}{mode==='飞机'?<Plane size={20}/>:mode.includes('高铁')?<TrainFront size={20}/>:<Car size={20}/>}</div><div><h3>{path}</h3><p>{mode}</p><span className="tag">{statusLabels[statuses[id]||'todo']}</span></div></article>)}</div><Card info={{kind:'tip',title:'衔接时留点余量',lines:['航班实际机场、车站名称、列车班次均需出票后确认。','高铁到站后再转预约接送；国庆车程与排队留足弹性。']}}/><a className="pill" href="#/bookings">去更新预订状态<ArrowRight size={16}/></a></>}
{route==='checklist'&&<><p className="eyebrow red">PACK LIGHT, TRAVEL WELL</p><h2>行李清单</h2><p className="muted">带上需要的，把轻松留给路上。</p><div className="packing-progress"><span>已准备 {packed} / {packingItems.length}</span><progress value={packed} max={packingItems.length}/></div>{packing.map(g=><section className="packing-group" key={g.title}><p className="eyebrow red">{g.en}</p><h3>{g.title}</h3>{g.items.map(item=><label key={item} className={checked[item]?'checked':''}><input type="checkbox" checked={!!checked[item]} onChange={e=>setChecked(s=>({...s,[item]:e.target.checked}))}/><span className="checkbox-art" aria-hidden="true">{checked[item]&&<Check size={15}/>}</span><span>{item}</span></label>)}</section>)}<p className="muted">勾选只保存在当前设备和浏览器；刷新后仍保留。</p></>}
{!routeIds.includes(route)&&<section className="info-card"><h2>没有找到这一页</h2><a className="pill" href="#/overview">返回旅行总览</a></section>}
</main><nav className="utility-nav" aria-label="旅行工具"><a aria-current={route==='overview'?'page':undefined} href="#/overview"><Map size={19}/>总览</a><a aria-current={route==='bookings'?'page':undefined} href="#/bookings"><CalendarCheck size={19}/>预订</a><a aria-current={route==='transport'?'page':undefined} href="#/transport"><TrainFront size={19}/>交通</a><a aria-current={route==='checklist'?'page':undefined} href="#/checklist"><BriefcaseBusiness size={19}/>行李</a></nav><footer>内蒙古 · 2026 秋<br/>方案更新于 {trip.updated}<br/>开放、天气、票价与班次以出发前官方信息为准。</footer>{printing&&<div className="print-all"><h1>{trip.title}</h1><p>2026年10月2日—8日 · 4位同行</p>{days.map(d=><section className="print-day" key={d.id}><DayPage day={d} statuses={statuses} onStatus={onStatus}/></section>)}</div>}</div>}

